import SiteHeader from '../../components/SiteHeader';
import SiteFooter from '../../components/SiteFooter';
import { eligibleMenu, getPackageRule, getPublicCatalog } from '../../../lib/catalog';

export const dynamic='force-dynamic';

export default async function PerformancePlanPage(){
  const catalog=await getPublicCatalog();
  const plan=catalog.packages.find(p=>p.slug==='performance');
  if(!plan) return <main className="siteShell"><SiteHeader/><section className="contentWidth sectionBlock"><div className="formCard"><h1>Performance plan is currently unavailable.</h1><a className="button buttonPrimary" href="/#plans">View active plans</a></div></section><SiteFooter/></main>;
  const rule=getPackageRule(catalog,plan.id); const options=(catalog.options||[]).filter(o=>o.package_id===plan.id&&o.active!==false); const sample=eligibleMenu(catalog,plan.id).slice(0,4);
  const breakfast=rule?.breakfast_qty??1, main=rule?.main_qty??1, snack=rule?.snack_qty??1;
  return <main className="siteShell"><SiteHeader/>
    <section className="contentWidth planDetailHero"><div className="planDetailCopy"><span className="eyebrow">{plan.name} plan</span><h1>{plan.tagline||'More protein. More progress. Less meal prep.'}</h1><p className="lead">{plan.description}</p><div className="planPriceLine"><strong>QAR {Number(plan.price_qar).toLocaleString()}</strong><span>{rule?.delivery_day_count||plan.duration_days} delivery-day package</span></div><div className="heroActions"><a className="button buttonPrimary" href={`/signup?plan=${plan.slug}`}>Choose {plan.name}</a><a className="button buttonSecondary" href={`/select?plan=${plan.slug}`}>Choose meals</a></div><div className="trustLine"><span>✓ Live package rules</span><span>✓ Backend-controlled meals</span><span>✓ Doha delivery</span></div></div><div className="planVisualCard"><img src={sample[0]?.image_url||'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=88'} alt="Healthy high protein meal"/><div className="floatingNutrition"><span>Daily target</span><strong>{plan.calories_min&&plan.calories_max?`${plan.calories_min.toLocaleString()}–${plan.calories_max.toLocaleString()} kcal`:'Flexible calories'}</strong><small>{plan.protein_target?`Approx. ${plan.protein_target}g protein target`:'Macros shown per meal'}</small></div></div></section>
    <section className="contentWidth sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">Live package rules</span><h2>Built around consistency.</h2></div><p>These quantities and eligible items are read from the same backend used by the customer selector and staff schedule.</p></div><div className="twoColumnGrid"><div className="featureList"><div className="featureListItem"><span className="checkIcon">✓</span><span>{breakfast} breakfast per delivery day</span></div><div className="featureListItem"><span className="checkIcon">✓</span><span>{main} main meal{main===1?'':'s'} per delivery day</span></div><div className="featureListItem"><span className="checkIcon">✓</span><span>{snack} snack{snack===1?'':'s'} per delivery day</span></div><div className="featureListItem"><span className="checkIcon">✓</span><span>{rule?.days_per_week??6} delivery days per week</span></div></div><div className="nutritionPanel"><span className="eyebrow">Package structure</span><div className="nutritionStat"><strong>{breakfast+main+snack}</strong><span>items / delivery day</span></div><div className="nutritionStat"><strong>{plan.protein_target||'—'}</strong><span>protein target g</span></div><div className="nutritionStat"><strong>{options.length||1}</strong><span>custom versions available</span></div></div></div></section>
    {options.length>0&&<section className="contentWidth sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">Customize your version</span><h2>Choose meals, snacks and days.</h2></div><p>Prices are configured by the admin and shown before you confirm the monthly schedule.</p></div><div className="sampleDayGrid">{options.map(option=><div className="sampleMeal" key={option.id}><span>QAR {Number(option.price_qar).toLocaleString()}</span><strong>{option.name}</strong><small>{option.breakfast_qty+option.main_qty+option.snack_qty} meals/day · {option.days_per_week} days/week · {option.delivery_day_count} delivery days</small></div>)}</div></section>}
    <section className="sectionTint"><div className="contentWidth sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">Eligible examples</span><h2>Loaded from the package mapping.</h2></div><a className="textButton" href={`/select?plan=${plan.slug}`}>Open meal selector →</a></div><div className="sampleDayGrid">{sample.map(meal=><div className="sampleMeal" key={meal.id}><span>{meal.category}</span><strong>{meal.name}</strong><small>{meal.calories} kcal • {Number(meal.protein_g)}g protein</small></div>)}</div></div></section>
    <section className="contentWidth sectionBlock"><div className="ctaBand"><div><span className="eyebrow lightEyebrow">{plan.name}</span><h2>Start your {rule?.delivery_day_count||plan.duration_days}-delivery-day plan for QAR {Number(plan.price_qar).toLocaleString()}.</h2></div><a className="button buttonLight" href={`/signup?plan=${plan.slug}`}>Create account</a></div></section><SiteFooter/>
  </main>;
}
