import SiteHeader from './components/SiteHeader';
import SiteFooter from './components/SiteFooter';
import { getPublicCatalog } from '../lib/catalog';

export const dynamic='force-dynamic';

export default async function HomePage(){
  const catalog=await getPublicCatalog();
  const featuredMeals=catalog.menu.slice(0,3);
  return <main className="siteShell"><SiteHeader/>
    <section className="heroSection" id="top"><div className="contentWidth heroGrid"><div className="heroCopy"><span className="eyebrow">Nutrition made practical</span><h1>Eat better without making food your full-time job.</h1><p className="lead">Choose your plan, pick only the meals included in that package, and manage delivery from one Nutripacks account.</p><div className="heroActions"><a className="button buttonPrimary" href="#plans">Explore meal plans</a><a className="button buttonSecondary" href="/menu">Browse live menu</a></div><div className="trustLine"><span>✓ Fresh prepared meals</span><span>✓ Clear nutrition data</span><span>✓ Package-based selection</span></div></div><div className="heroVisual"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=90" alt="Fresh prepared meal"/><div className="heroFloat topFloat"><small>Live packages</small><strong>{catalog.packages.length}</strong><span>available plans</span></div><div className="heroFloat bottomFloat"><span className="dot"/><div><strong>Live menu rules</strong><small>Managed from admin</small></div></div></div></div></section>
    <section className="proofStrip"><div className="contentWidth proofGrid"><div><strong>{catalog.packages.length}</strong><span>active meal plans</span></div><div><strong>{catalog.menu.length}</strong><span>active menu items</span></div><div><strong>TEST</strong><span>no payment required</span></div><div><strong>100%</strong><span>visible macros</span></div></div></section>
    <section className="contentWidth sectionBlock" id="plans"><div className="sectionHeading"><div><span className="eyebrow">Meal plans</span><h2>Pick the structure that fits your goal.</h2></div><p>These packages are loaded directly from the Nutripacks database. Admin changes appear here automatically.</p></div><div className="planGrid">{catalog.packages.map(plan=><article className={plan.featured?'planCard featuredPlan':'planCard'} key={plan.id}>{plan.featured&&<span className="popularBadge">Most popular</span>}<span className="eyebrow">{plan.tagline||'Meal plan'}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className="planPrice"><strong>QAR {Number(plan.price_qar).toLocaleString()}</strong><span>/ {plan.duration_days} days</span></div><div className="planFacts"><span>{plan.meals_per_day} items / day</span><span>{plan.calories_min&&plan.calories_max?`${plan.calories_min.toLocaleString()}–${plan.calories_max.toLocaleString()} kcal`:'Flexible calories'}</span><span>{plan.protein_target?`${plan.protein_target}g protein target`:'Clear macros'}</span></div><a className={plan.featured?'button buttonLight fullButton':'button buttonPrimary fullButton'} href={`/select?plan=${encodeURIComponent(plan.slug)}`}>Choose {plan.name}</a></article>)}</div></section>
    <section className="sectionTint" id="menu"><div className="contentWidth sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">Live menu</span><h2>Food first. Numbers included.</h2></div><div><p>Calories, protein, carbs, fats, tags and allergens come from the backend.</p><a className="textButton" href="/menu">Explore the full menu →</a></div></div><div className="featuredMealGrid">{featuredMeals.map(meal=><article className="mealCard" key={meal.id}><div className="mealImageWrap"><img className="mealImage" src={meal.image_url||'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=85'} alt={meal.name}/><span className="mealType">{meal.category}</span></div><div className="mealBody"><div className="mealTitleRow"><h3>{meal.name}</h3><strong>{meal.calories}<small> kcal</small></strong></div><div className="macroHighlight"><span>Protein</span><strong>{Number(meal.protein_g)}g</strong></div></div></article>)}</div></div></section>
    <section className="contentWidth sectionBlock" id="how"><div className="sectionHeading centeredHeading"><div><span className="eyebrow">How it works</span><h2>Signup to kitchen schedule, all connected.</h2></div></div><div className="stepsGrid"><article><span className="stepNumber">01</span><h3>Create your profile</h3><p>Add delivery details, goals and allergies.</p></article><article><span className="stepNumber">02</span><h3>Choose a live package</h3><p>The package rules decide quantities and eligible items.</p></article><article><span className="stepNumber">03</span><h3>Select your meals</h3><p>Only items assigned to your package are shown.</p></article><article><span className="stepNumber">04</span><h3>Kitchen sees the schedule</h3><p>Chef and sales views update from customer selections.</p></article></div></section>
    <section className="contentWidth sectionBlock" id="faq"><div className="sectionHeading"><div><span className="eyebrow">FAQ</span><h2>Testing the complete customer flow.</h2></div><p>This environment is for validating packages, meals, schedules and staff workflows before production.</p></div><div className="faqGrid"><details open><summary>Do I need to pay in this environment?</summary><p>No. Orders activate immediately after the customer saves a complete meal schedule.</p></details><details><summary>Can admins edit packages and menu items?</summary><p>Yes. Packages, menu items and eligibility rules are managed from the admin catalog.</p></details><details><summary>Can customers change selections?</summary><p>Yes. Existing orders can be reopened from the customer account and edited while the testing environment is active.</p></details><details><summary>Do Chef and Sales see the same data?</summary><p>Chef sees production quantities without customer contact information. Sales and Admin can see customer and delivery details.</p></details></div></section>
    <section className="contentWidth sectionBlock"><div className="ctaBand"><div><span className="eyebrow lightEyebrow">Ready</span><h2>Build your first delivery week.</h2></div><a className="button buttonLight" href="/signup">Create your account</a></div></section><SiteFooter/>
  </main>;
}
